core/urls.py
from django.urls import path, re_path, reverse


from . import views
from apps.dashboard.catalogue.views import TlinkProductCreateUpdateView

app_name='core'
urlpatterns = [
    path('', views.indexList.as_view() , name='index'),
    path('search/', views.ProductStoreSearch.as_view(), name='search'),
    path('subscribe/', views.Subscribe.as_view(), name='subscribe'),
    re_path(
                r"^products/create/(?P<product_class_slug>[\w-]+)/$",
                TlinkProductCreateUpdateView.as_view(),
                name="catalogue-product-create",
            ),
]

store/urls.py
from django.urls import path, re_path

from . import views
from apps.dashboard.catalogue import views as  OscarViews

app_name='store'
urlpatterns = [
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('settings/store/update', views.StoreCreationView.as_view(), name='updateStore'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/delete/', views.ProfileDeleteView.as_view(), name='profile-delete'),
    path('profile/change_password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('<int:pk>/follow/store/', views.FollowView.as_view(), name='follow'),
    path('<int:pk>/dashboard/', views.DashBoardView.as_view(), name='dashboard'),
    path('product_addition/<str:category>/', views.ProductCreation.as_view(), name='add_product'),
    path('<int:pk>/<slug:slug>/store', views.StoreView.as_view(), name='store'),
    path('upload-profile-image/', views.UploadProfileImageView.as_view(), name='profile_upload'),
    path('filter/products_by/<str:product_class>/<int:pk>/<slug:slug>', views.ProductClassFilterView.as_view(), name='productclass'),
    path('<int:pk>/<slug:slug>/comment-on-store/', views.StoreCommentView.as_view(), name="comment"),
    path('<int:pk>/vote/comment', views.AddVoteView.as_view() , name='add-vote'),
    path('<int:comment_pk>/reply/comment', views.CommentReplyView.as_view(), name='reply'),
    path('create/store/settings', views.StoreCreationView.as_view(),  name="createStore"),
    re_path(
                r"^products/create/(?P<product_class_slug>[\w-]+)/$",
                OscarViews.TlinkProductCreateUpdateView.as_view(),
                name="product_create",
            ),
   
]

tlink_django/urls.py
from django.conf import settings
from django.apps import apps
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('tlink/', include('store.urls')),
    path('', include(apps.get_app_config('oscar').urls[0])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

apps/dashboard/catalogue/models.py
from oscar.apps.dashboard.catalogue.models import * 

apps/dashboard/catalogue/forms.py
from oscar.apps.dashboard.catalogue.forms import ProductForm as OscarProductForm, ProductClassForm as OscarProductClassForm
from oscar.apps.dashboard.catalogue.forms import StockRecordForm as OscarStockRecordForm


from apps.catalogue.models import Product,  ProductClass
from apps.partner.models import Partner



class StockRecordForm(OscarStockRecordForm):
    class Meta(OscarStockRecordForm.Meta):
      pass

    def __init__(self, product_class, user ,*args, **kwargs):
        super().__init__(product_class, user, *args, **kwargs)
        self.user = user
        self.fields['partner'].widget.attrs.update({'class':'form-select'})
        self.fields['partner_sku'].widget.attrs.update({'class':'form-control'})
        self.fields['price_currency'].widget.attrs.update({'class':'form-control'})
        self.fields['price'].widget.attrs.update({'class':'form-control'})
        self.fields['num_in_stock'].widget.attrs.update({'class':'form-control'})
        self.fields['low_stock_threshold'].widget.attrs.update({'class':'form-control'})


        # Set the user as the default patner to the shop
        if bool(user.partners.all()) == False:
            partner, created = Partner.objects.get_or_create(name=user.shop.name)
            user.partners.add(partner)
    

        if not self.user.is_staff:
            self.fields["partner"].queryset = self.user.partners.all()



class ProductForm(OscarProductForm):
    class Meta(OscarProductForm.Meta):
        fields = OscarProductForm.Meta.fields + ['condition']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class':'form-control'})
        self.fields['condition'].widget.attrs.update({'class':'form-select'})
        self.fields['is_public'].widget.attrs.update({'class':'form-check'})
        self.fields['upc'].widget.attrs.update({'class':'form-control'})
        self.fields['description'].widget.attrs.update({'class':'form-control', 'cols':40, 'rows': 5, 'placeholder':'Give a product description'})

class ProductClassForm(OscarProductClassForm):
    class Meta(OscarProductClassForm.Meta):
        model = ProductClass
        fields = ["name", "category", "requires_shipping", "track_stock", "options"]
    
    

apps/dashboard/catalogue/views.py
from oscar.apps.dashboard.catalogue.views import ProductCreateUpdateView , ProductClassCreateView as OscarProductClassCreateView
from oscar.apps.dashboard.catalogue.views import ProductListView as OscarProductListView

from django.urls import reverse
from django.shortcuts import render

from .forms import ProductForm, ProductClassForm
from .formsets import StockRecordFormSet
from .tables import ProductTable


class ProductListView(OscarProductListView):
    table_class = ProductTable


class TlinkProductCreateUpdateView(ProductCreateUpdateView):
    template_name = "store/dashboard/product_addition.html"
    form_class = ProductForm
    stockrecord_formset = StockRecordFormSet

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.formsets = {
            "image_formset": self.image_formset,
            "stockrecord_formset": self.stockrecord_formset,
        }


    def form_valid(self, form ,*args, **kwargs):
        product = form.save(commit=False)
        product.seller = self.request.user
        product.save()
        
        # Add the product to the current user's store
        self.request.user.shop.record.products.add(product)
        product.categories.add(self.get_context_data()['product_class'].category)
    
        response = super().form_valid(form, *args, **kwargs)

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def get_success_url(self, **kwargs):
        super().get_success_url(**kwargs)
        action = self.request.POST.get("action")
        if action == "continue":
            url = reverse("dashboard:catalogue-product", kwargs={"pk": self.object.id})
        else:
            url = reverse("store:dashboard", kwargs={'pk':self.request.user.pk})
        return self.get_url_with_querystring(url)

        
class ProductClassCreateView(OscarProductClassCreateView):
    form_class= ProductClassForm
    
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

store/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import TemplateView, View, DetailView, ListView
from django.views.generic.edit import FormView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

from django.utils import timezone

from .signals import store_viewed
from core.mixins import BaseContextMixin




from .forms import StoreForm, CommentForm, PasswordChangeForm, VoteForm,ReplyForm
from core.models import User
from .models import Store, Product, StoreRecord, Comment
from .mixins import settingsMixin, PageTitleMixin, StoreMixin



from apps.dashboard.catalogue.views import ProductListView
from apps.customer.views import ProfileUpdateView, ProfileDeleteView, ChangePasswordView
from apps.customer.views import ProfileView
from apps.catalogue.models import Category



class SettingsView(settingsMixin, ProfileView):
    template_name = 'store/store_settings_details.html'
    active_tab = 'store_settings'
    page_title = 'Profile'


class ProfileUpdateView(settingsMixin, ProfileUpdateView):
    template_name = 'store/profile_form.html'
    active_tab = 'profile'
    success_url = reverse_lazy('store:settings')

class ProfileDeleteView(settingsMixin, ProfileDeleteView):
    template_name = 'store/profile_delete.html'
    active_tab = 'profile'
    success_url = reverse_lazy('core:index')


class ChangePasswordView(settingsMixin, ChangePasswordView):
    form_class = PasswordChangeForm
    template_name = 'store/change_password.html'
    success_url = reverse_lazy('store:settings')


class StoreCreationView(SettingsView):
    """
     Get the existing user store and create a form for updating it.

    """
    template_name = 'store/store_settings_form.html'
    form_class = StoreForm
    model = User
    active_tab = 'store_settings'

   

    def post(self, request, *args, **kwargs):
        storeForm = self.form_class(request.POST, request.FILES)

        if storeForm.is_valid():
           store = storeForm.save(commit=False)
           store.slug = store.get_slug()
           store.prompted = True
           store.owner = request.user
           store.primary_image = request.user.profile_image
           store.save()
           storeForm.save_m2m()

           # Create a store record if it does not exist
           store_record_exists = StoreRecord.objects.filter(store=store).exists()

           if not store_record_exists:
                store_record =  StoreRecord.objects.create(store=store)
                store_record.staff.add(request.user)

           message = "Your store has successfully been created. Enjoy"
           messages.success(request, message)
           return redirect(reverse('store:settings'))
        else:
            context = self.get_context_data(storeForm=storeForm)
            return render(request, self.template_name, context)
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        for kw in kwargs:
            context[kw] = kwargs[kw]
        return context
        
        
class UploadProfileImageView(View):
    def post(self, request, *args, **kwargs):
        new_image = request.FILES.get('profile-image')

        request.user.profile_image = new_image
        request.user.save()
        # Update Store image
        if hasattr(request.user, 'shop'):
            request.user.shop.primary_image = request.user.profile_image
            request.user.shop.save()
        new_image_url = request.user.profile_image.url

        return JsonResponse({'new_image': new_image_url })
    
class FollowView(LoginRequiredMixin, BaseContextMixin, StoreMixin, View):
    model =Store
    template_name = 'store/store.html'

    def get(self, request , *args, **kwargs):
        store = self.get_store()
        return redirect(reverse('store:store', kwargs={'pk': store.pk, 'slug': store.get_slug()}))

    def post(self, request, *args, **kwargs):
        store_id = int(request.POST['store_id'])
        store = Store.objects.filter(id=store_id).first()

        if request.user in store.record.store_followers.all():
            store.record.store_followers.remove(request.user)
            is_follower = False
        else:
            store.record.store_followers.add(request.user)
            is_follower = True

        followers_count = store.record.store_followers.all().count()
        

        return JsonResponse({'followers_count': followers_count, 'is_follower': is_follower}) 



class StoreView(BaseContextMixin, StoreMixin, ListView):
    model = Product
    template_name='store/store.html'
    paginate_by= settings.STORE_PRODUCTS_PER_PAGE
    context_object_name ='products'
   
    form_class = CommentForm
    view_signal = store_viewed

    def get(self, request, *args, **kwargs):  
        self.store = self.get_store(**kwargs)

        
        if request.user.is_authenticated:
            if not self.store == request.user.shop:
                self.send_signal(store=self.store, user=request.user , datetime=timezone.now())
        return super().get(request, *args, **kwargs)
    
    def send_signal(self, user, store, datetime):
        self.view_signal.send(
            sender=self,
            store=store,
            user= user,
            datetime=datetime
        )


class ProductClassFilterView(StoreView):
    model=Product
    def get_store(self, **kwargs):
        return get_object_or_404(Store, pk=self.kwargs['pk'], slug=self.kwargs['slug'])
    
    def get_queryset(self,*args,**kwargs):
        print(self.kwargs)
        queryset= self.store.record.products.filter(product_class__name=self.kwargs['product_class']).browsable().base_queryset()
        return queryset

    


class StoreCommentView(StoreView):
    def post(self, request, *args, **kwargs):
        self.store = self.get_store(**kwargs)
        self.object_list = self.get_queryset()
        commentForm = self.form_class(data=request.POST, store=self.store, user=request.user)
       
        if commentForm.is_valid():
            comment = commentForm.save(commit=False)
            comment.store = self.store
            comment.user = request.user
            comment.save()
            return redirect(reverse('store:store', kwargs={'pk': self.store.pk, 'slug': self.store.get_slug()}))
        
        return render(request, self.template_name, self.get_context_data(commentForm = commentForm))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        for kw in kwargs:
            context[kw] = kwargs[kw]
        return context


class DashBoardView(ProductListView):
    model = Product
    template_name = 'store/dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = Category.objects.all()
        root_categories = []

        for category in categories:
            if category.is_root():
                root_categories.append(category)
        
        

        context['categories'] = root_categories
        return context


class ProductCreation(TemplateView):
    template_name='store/dashboard/product_addition.html'


    def get(self, request, *args, **kwargs ):
        """
            Set a limit to the number of products based on the subscription package:
            Basic - 15 products
            Premium - 30 products
            Enterprise - Unlimited products

        """
        is_enterprise = False
        if request.user.groups.all().first().name == 'Enterprise':
            is_enterprise = True

        if request.user.is_authenticated and not is_enterprise  :
            user_product_count = request.user.shop.record.products.count()
            user_group = request.user.groups.all().first().name
            product_limit = settings.BASIC_PRODUCT_LIMIT
            if user_group == 'Premium':
                product_limit = settings.PREMIUM_PRODUCT_LIMIT
           

            if user_product_count >= product_limit:
                messages.error(request, 'Update to premium or enterprise to add more products')
                return redirect(reverse('store:dashboard', kwargs={'pk': request.user.pk}))
            
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['root_category'] = Category.objects.get(name=kwargs['category'])
        context['productclass_categories'] = context['root_category'].get_descendants().filter(productclass__isnull=False).distinct()
        return context


class AddVoteView(StoreView ):
    """
    Simple view for voting on a review.

    We use the URL path to determine the product and review and use a 'delta'
    POST variable to indicate it the vote is up or down.
    """

    def post(self, request, *args, **kwargs):     
        comment  = get_object_or_404(Comment, pk=self.kwargs["pk"])
        errors = []

        form = VoteForm(comment, request.user, request.POST)
        if form.is_valid():
            if form.is_up_vote:
                comment.vote_up(request.user)
            elif form.is_down_vote:
                comment.vote_down(request.user)
                 
        else:
            for error_list in form.errors.values():
                for msg in error_list:
                    errors.append(msg)

        has_up_vote = comment.votes.filter(user=request.user, delta=1).exists()
        has_down_vote = comment.votes.filter(user=request.user, delta=-1).exists()

        
        data = {
            'errors': errors,
            'has_up_vote': has_up_vote,

store/templates/store/dashboard/base.html
{% extends 'oscar/base.html' %}
{% load static %}
{% load image_tags %}
{% block extrastyles %}
{{ block.super  }}
<link rel="stylesheet" href="{% static 'oscar/js/bootstrap4-datetimepicker/tempusdominus-bootstrap-4.min.css' %}" />
<link rel="stylesheet" href="{% static 'store/CSS/dashboard.css' %}">
{% endblock %}

{% block layout %}
<div class="contaniner-fluid">
	<!-------------Left side bar----------->
	<div class="modal fade " tabindex="-1" id="category_select" >
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title ">Choose  product category </h5>
                    <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
						{% for category in categories %}
						{% if category in user.shop.product_type.all %}
						<div class="col-lg-4 col-md-4 col-6 my-2">
							<a href="{% url 'store:add_product' category.name %}">
								<div class="image-container" class="w-25">
								  <img src="{% oscar_thumbnail category.image  '300x400' crop='center' upscale='false' %}" alt="" class="rounded img-fluid">
								  <div class="image-info">
									<h6 class="text-white  text-uppercase  fs-6">{{ category.name }}</h6>
								</div>
							  </div>
							  </a>
						</div>
						{% endif %}
						{% endfor %}
					</div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" data-bs-dismiss="modal" >Cancel</button>
                </div>

            </div>
        </div>
</div>
		<div class="navigation">
			<ul>
				<li class="excluded">
					<a href="{% url 'store:dashboard' user.pk %}">
						<span class="sidenav-title h3 mt-3 fw-bold text-uppercase">Dashboard</span>
					</a>
				</li>

				<li class="side-title">
					<span class="sidenav-title text-white text-uppercase ">Main</span>
				</li>
				<li>
					<a href="{% url 'core:index' %}">
						<span class="icon">
							<i class="bi bi-house-fill"></i>
						</span>
						<span class="sidenav-title">
							Home
						</span>
					</a>
				</li>
				<li>
					<a href="{% url 'store:store' user.shop.pk user.shop.get_slug %}">
						<span class="icon">
							<i class="bi bi-shop"></i>
						</span>
						<span class="sidenav-title">
							MyStore
						</span>
					</a>
				</li>
				<li>
					<a href="{% url 'store:settings'   %}">
						<span class="icon">
							<i class="bi bi-gear"></i>
						</span>
						<span class="sidenav-title">
							Account
						</span>
					</a>
				</li>
				<hr ><!--Break point-->
				<li class="side-title">
					<span class="sidenav-title text-white text-uppercase ">Tables</span>
				</li>
				<li>
					<a href="">
						<span class="icon">
							<i class="bx bxs-t-shirt"></i>
						</span>
						<span class="sidenav-title">
							Fashion
						</span>
					</a>
				</li>
				<li>
					<a href="">
						<span class="icon">
							<i class="bi bi-phone-landscape"></i>
						</span>
						<span class="sidenav-title">
							Electronics
						</span>
					</a>
				</li>
				<li>
					<a href="">
						<span class="icon">
							<i class="bi bi-bag-heart"></i>
						</span>
						<span class="sidenav-title">
							Supermarket
						</span>
					</a>
				</li>
				<li>
					<a href="">
						<span class="icon">
							<i class="bi bi-pen"></i>
						</span>
						<span class="sidenav-title">
							Scholastics
						</span>
					</a>
				</li>
			</ul>
		</div>
	<!----End of Left sidebar-->
	<!--==========Main==================-->
	<div class="main ">
		<div class="topbar">
			<div class="toggle">
				<i class="bx bx-menu"></i>
			</div>
	
			
			<div class="profile d-flex align-items-center ">
				<div class="add-btn mx-2">
					<button  class="btn rounded-pill btn-primary fw-bold fs-6 d-none d-md-block d-lg-block text-center" data-bs-toggle="modal" data-bs-target="#category_select">Add product+</button>
					<button  class="btn rounded-pill btn-primary fw-bold btn-sm d-block d-md-none d-lg-none text-center" data-bs-toggle="modal" data-bs-target="#category_select">Add+</button>
				</div>
				<div class="notifications position-relative mx-1">
					<i class="bi bi-bell fs-4"></i>
					<span class=" translate-middle badge rounded-pill bg-danger">99+</span>
				</div>
				<div class="user  mx-2">
					<img src="{% static 'core/Images/9973ae95495ad119d5ee1894ee121f1c.jpg' %}" alt="Profile image" class="user-profile-img">	
				</div>
				<div class="profile-links">
					<ul class="list-group">
						<li class="fw-bold list-group-item"><a href="{% url 'store:settings'  %}">Account</a></li>
						<li  class="fw-bold list-group-item " ><a href="{% url 'customer:logout' %}">Logout</a></li>
						{% if user.is_superuser %}
						<li  class="fw-bold list-group-item">
						<a class="nav-link mx-lg-2" href="{% url 'dashboard:index' %}">Oscar</a>
						</li>
						<li  class="fw-bold list-group-item">
						<a class="nav-link mx-lg-2" href="/admin">Admin</a>
						</li>
						{% endif %}
					</ul>
				</div>
			
			</div>
		</div>		
			{% block dashboard_content %}
			
			{% endblock %}

		{% include 'oscar/partials/backtotop.html' %}
{% include 'oscar/partials/footer.html' %}
	</div>
</div>


{% endblock %}

{% block extrascripts %}
{{ block.super }}


	<script src="{% static 'store/Javascript/dashboard.js' %}"></script>
{# jQuery plugins #}
    <script src="{% static 'oscar/js/mousewheel/jquery.mousewheel.js' %}"></script>
    <script src="{% static 'oscar/js/bootstrap4-datetimepicker/moment-with-locales.min.js' %}"></script>
    <script src="{% static 'oscar/js/bootstrap4-datetimepicker/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script src="{% static 'oscar/js/inputmask/jquery.inputmask.min.js' %}"></script>
    <script src="{% static 'oscar/js/jquery-sortable/jquery-sortable-min.js' %}"></script>
    <script src="{% static 'oscar/js/oscar/dashboard.js' %}"></script>
    <script src="{% static 'oscar/js/oscar/RelatedObjectLookups.js' %}"></script>
    <script src="{% static 'oscar/js/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'oscar/js/tinymce/jquery.tinymce.min.js' %}"></script>

{% endblock %}


{% block onbodyload %}
    {{ block.super }}

    // Javascript to enable link to tab
    var url = document.location.toString();
    if (url.match('#')) {
        $('.bs-docs-sidenav a[href="#' + url.split('#')[1] + '"]').tab('show');
    }

    // Change hash for page-reload
    $('.nav-list a').on('shown.bs.tab', function (e) {
        window.location.hash = e.target.hash;
    });

    options = {
      'languageCode': '{{ LANGUAGE_CODE }}'
    };
    oscar.dashboard.init(options);

	$(document).ready(function(){
		console.log('Running')
		oscar.dashboard.filereader.init()
	})
{% endblock %}

store/templates/store/dashboard/dashboard.html
{% extends 'store/dashboard/base.html' %}
{% load static %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block dashboard_content %}
<div class="container-fluid my-3">

	{% if messages %}
	{% for message in messages %}
	   <div class="alert alert-success alert-dismissible fade show  box fw-bold fs-6 my-3" role="alert">
	   <p>{{ message }}</p>
	   <span class="btn-close" data-bs-dismiss="alert" aria-label="Close"></span>
		</div>
	   {% endfor %}
   {% endif %}

   
	{% block dashboard_cards %}
	<div class="row" id="topcards">
		<div class="col-md-3 col-sm-6 col-lg-3 my-2 ">
			<div class="card  rounded-5">
				<a href="">
					<div class="card-body  bg-primary text-warning text-center fw-bold border border-primary-subtle rounded-5">
						<h3>15000</h3>
						<span class="lead  fw-bold ">Weekly Traffic</span>
					</div>
				</a>
			</div>
		</div>
			<div class="col-md-3 col-sm-6 col-lg-3 my-2 ">
				<a href="">
					<div class="card rounded-5">
						<div class="card-body  text-bg-secondary bg-primary text-center fw-bold border border-primary-subtle rounded-5">
							<h3>145</h3>
							<span class="lead  fw-bold ">Products</span>
						</div>
					</div>
				</a>
			</div>
			<div class="col-md-3 col-sm-6 col-lg-3 my-2 ">
				<a href="">
					<div class="card rounded-5">
						<div class="card-body  text-bg-secondary bg-primary text-center fw-bold border border-primary-subtle rounded-5">
							<h3>40</h3>
							<span class="lead  fw-bold ">Orders</span>
						</div>
					</div>
				</a>
			</div>
	
			<div class="col-md-3 col-sm-6 col-lg-3 my-2 ">
				<a href="">
					<div class="card rounded-5">
						<div class="card-body  text-bg-secondary bg-primary text-center fw-bold border border-primary-subtle rounded-5">
							<h3>324</h3>
							<span class="lead  fw-bold ">Followers</span>
						</div>
					</div>
				</a>
			</div>
	</div>	
	{% endblock %}
	
	

	{% block dashboard_tables %}
			<div class="my-3">
		{% if products %}
			{% block product_list %}
				<form method="post">
					{% csrf_token %}
					{% render_table products %}
				</form>
				<div class="modal fade" id="product-image-modal" tabindex="-1" role="dialog">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h4 class="modal-title"></h4>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							</div>
							<div class="modal-body text-center">
								<img class="img-fluid mx-auto">
							</div>
						</div>
					</div>
				</div>
			{% endblock product_list %}
		{% else %}
			<p>{% trans "No products found." %}</p>
		{% endif %}
			</div>
	{% endblock dashboard_tables %}
</div>
{% endblock %}