core/urls.py
from django.urls import path, re_path, reverse


from . import views
from apps.dashboard.catalogue.views import TlinkProductCreateUpdateView

app_name='core'
urlpatterns = [
    path('', views.indexList.as_view() , name='index'),
    path('search/', views.ProductStoreSearch.as_view(), name='search'),
    path('subscribe/', views.Subscribe.as_view(), name='subscribe'),
    re_path(
                r"^products/create/(?P<product_class_slug>[\w-]+)/$",
                TlinkProductCreateUpdateView.as_view(),
                name="catalogue-product-create",
            ),
]

store/urls.py
from django.urls import path, re_path

from . import views
from apps.dashboard.catalogue import views as  OscarViews

app_name='store'
urlpatterns = [
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('settings/store/update', views.StoreCreationView.as_view(), name='updateStore'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/delete/', views.ProfileDeleteView.as_view(), name='profile-delete'),
    path('profile/change_password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('<int:pk>/follow/store/', views.FollowView.as_view(), name='follow'),
    path('<int:pk>/dashboard/', views.DashBoardView.as_view(), name='dashboard'),
    path('product_addition/<str:category>/', views.ProductCreation.as_view(), name='add_product'),
    path('<int:pk>/<slug:slug>/store', views.StoreView.as_view(), name='store'),
    path('upload-profile-image/', views.UploadProfileImageView.as_view(), name='profile_upload'),
    path('filter/products_by/<str:product_class>/<int:pk>/<slug:slug>', views.ProductClassFilterView.as_view(), name='productclass'),
    path('<int:pk>/<slug:slug>/comment-on-store/', views.StoreCommentView.as_view(), name="comment"),
    path('<int:pk>/vote/comment', views.AddVoteView.as_view() , name='add-vote'),
    path('<int:comment_pk>/reply/comment', views.CommentReplyView.as_view(), name='reply'),
    path('create/store/settings', views.StoreCreationView.as_view(),  name="createStore"),
    re_path(
                r"^products/create/(?P<product_class_slug>[\w-]+)/$",
                OscarViews.TlinkProductCreateUpdateView.as_view(),
                name="product_create",
            ),
   
]

tlink_django/urls.py
from django.conf import settings
from django.apps import apps
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('tlink/', include('store.urls')),
    path('', include(apps.get_app_config('oscar').urls[0])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

apps/dashboard/catalogue/models.py
from oscar.apps.dashboard.catalogue.models import * 

store/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.db.models import Count, Sum
from core.models import User
from datetime import datetime 
from django.core.exceptions import ValidationError

from .managers import CommentQuerySet


from apps.catalogue.models import Category, Product

class Store(models.Model):
    LOCATION_CHOICES =[('BW', 'Bweyale'), ('KY', 'Kyradongo')]
  
    name = models.CharField(max_length=15)
    owner = models.OneToOneField(User, related_name="shop", on_delete=models.CASCADE)
    location = models.CharField(max_length=20, choices=LOCATION_CHOICES)
    product_type  = models.ManyToManyField(Category)
    is_active = models.BooleanField(default=False)
    slug = models.SlugField()
    date_created = models.DateField('Date created', auto_now_add=True)
    date_modified = models.DateTimeField('Date modified', auto_now=True)
    primary_image = models.ImageField(upload_to='store')
    location_image1 = models.ImageField(upload_to='location', default='image_not_found.jpg')
    location_image2 = models.ImageField(upload_to='location', default='image_not_found.jpg')
    location_image3 = models.ImageField(upload_to='location', default='image_not_found.jpg')
    location_image4 = models.ImageField(upload_to='location', default='image_not_found.jpg')

    def __str__(self):
        return self.name
    
    def get_slug(self):
        return slugify(self.name)


    def get_absolute_url(self):
        """
            Get the store 
        """
        return reverse('store:store', kwargs={'pk': self.pk , 'slug':self.slug})

    
    def update_rating(self):
        """
        Recalculate rating field
        """
        self.record.rating = self.calculate_rating()
        self.record.save()

    update_rating.alters_data = True

    def calculate_rating(self):
        """
        Calculate rating value
        """
        result = self.comments.filter(type='PC').aggregate(
            sum=Sum("score"), count=Count("id")
        )
        reviews_sum = result["sum"] or 0
        reviews_count = result["count"] or 0
        rating = None
        if reviews_count > 0:
            rating = float(reviews_sum) / reviews_count
        return rating

class StoreRecord(models.Model):
    store = models.OneToOneField(Store, on_delete=models.CASCADE ,  related_name='record')
    views = models.IntegerField(default=0)
    # Ratings are between 0 and 5
    RATING_CHOICES = tuple([(x, x) for x in range(0, 6)])
    rating = models.PositiveSmallIntegerField( "Rating", choices=RATING_CHOICES, default=0)
    products = models.ManyToManyField(Product, related_name='store_record', blank=True)
    staff = models.ManyToManyField(User, related_name='stores')
    store_followers = models.ManyToManyField(User, through='FollowInfo')

    def __str__(self):
        return self.store.name
    
class FollowInfo(models.Model):
    follower_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followed_store')
    store_record = models.ForeignKey(StoreRecord, on_delete=models.CASCADE)
    date_followed = models.DateTimeField(auto_now_add=True)

class UserStoreRecord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    no_of_views = models.PositiveBigIntegerField()
    date_viewed = models.DateTimeField(auto_now_add=True)
    last_viewed = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    TYPE_CHOICES = [
        ('PC', 'Parent Comment'),
        ('R', 'Reply')
    ]
    title = models.CharField(max_length=30)
    user = models.ForeignKey(User, related_name='comment_user', on_delete=models.CASCADE)
    message = models.TextField('Body')
    type = models.CharField(max_length=16, choices=TYPE_CHOICES, default='PC')
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    total_votes = models.IntegerField('Total votes', default=0)
    delta_votes = models.IntegerField('Delta Votes', default=0)
    
    date_created = models.DateField('Date created', auto_now_add=True)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name='comments')
    # Scores are between 0 and 5
    SCORE_CHOICES = tuple([(x, x) for x in range(0, 6)])
    score = models.PositiveSmallIntegerField( "Score", choices=SCORE_CHOICES)

    objects = CommentQuerySet.as_manager()


    class Meta:
        ordering = ["-delta_votes", "id"]

    def __str__(self):
        return self.title
    
    def vote_up(self, user):
        self.votes.create(user=user, delta=Vote.UP)

    def vote_down(self, user):
        self.votes.create(user=user, delta=Vote.DOWN)

    def can_user_vote(self, user):
        """
        Test whether the passed user is allowed to vote on this
        review
        """
        if not user.is_authenticated:
            return False, _("Only signed in users can vote")
        # pylint: disable=no-member
        vote = self.votes.model(comment=self, user=user, delta=1)
        try:
            vote.full_clean()
        except ValidationError as e:
            return False, "%s" % e
        return True, ""
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.store.update_rating()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        if self.store is not None:
            self.store.update_rating()

    
    def update_totals(self):
        """
        Update total and delta votes
        """
        result = self.votes.aggregate(score=Sum("delta"), total_votes=Count("id"))
        self.total_votes = result["total_votes"] or 0
        self.delta_votes = result["score"] or 0
        self.save()

    @property
    def is_anonymous(self):
        return self.user is None
    
    @property
    def has_votes(self):
        return self.total_votes > 0

    @property
    def num_up_votes(self):
        """Returns the total up votes"""
        return int((self.total_votes + self.delta_votes) / 2)

    @property
    def num_down_votes(self):
        """Returns the total down votes"""
        return int((self.total_votes - self.delta_votes) / 2)
    
    @property
    def has_replies(self):
        """Return true if comment has replies"""
        return self.replies.filter().exists()
    @property
    def is_parent(self):
        """Returns true is comment is a parent comment"""
        if self.type == 'PC':
            return True
        else:
            return False
    

class Vote(models.Model):
    """
    Records user comment as yes/no vote.

    * Only signed-in users can vote.
    * Each user can vote only once.
    """

    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="votes"
    )
    user = models.ForeignKey(
        User, related_name="comment_votes", on_delete=models.CASCADE
    )
    UP, DOWN = 1, -1
    VOTE_CHOICES = ((UP, "Up"), (DOWN, "Down"))
    delta = models.SmallIntegerField("Delta", choices=VOTE_CHOICES)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date_created"]
        verbose_name = "Comment Vote"
        verbose_name_plural = "Comment Votes"

    def __str__(self):
        return "%s vote for %s" % (self.delta, self.comment)
    
    def clean(self):
        if not self.comment.is_anonymous and self.comment.user == self.user:
            raise ValidationError("You cannot vote on your own comment")
        if not self.user.id:
            raise ValidationError("Only signed-in users can vote on comments")
        previous_votes = self.comment.votes.filter(user=self.user)
        if len(previous_votes) > 0:
            print(previous_votes)
            previous_votes.delete()
            # raise ValidationError("You can only vote once on a review")



    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.comment.update_totals()



    

apps/dashboard/catalogue/forms.py
from oscar.apps.dashboard.catalogue.forms import ProductForm as OscarProductForm, ProductClassForm as OscarProductClassForm
from oscar.apps.dashboard.catalogue.forms import StockRecordForm as OscarStockRecordForm


from apps.catalogue.models import Product,  ProductClass
from apps.partner.models import Partner



class StockRecordForm(OscarStockRecordForm):
    class Meta(OscarStockRecordForm.Meta):
      pass

    def __init__(self, product_class, user ,*args, **kwargs):
        super().__init__(product_class, user, *args, **kwargs)
        self.user = user
        self.fields['partner'].widget.attrs.update({'class':'form-select'})
        self.fields['partner_sku'].widget.attrs.update({'class':'form-control'})
        self.fields['price_currency'].widget.attrs.update({'class':'form-control'})
        self.fields['price'].widget.attrs.update({'class':'form-control'})
        self.fields['num_in_stock'].widget.attrs.update({'class':'form-control'})
        self.fields['low_stock_threshold'].widget.attrs.update({'class':'form-control'})


        # Set the user as the default patner to the shop
        if bool(user.partners.all()) == False:
            partner, created = Partner.objects.get_or_create(name=user.shop.name)
            user.partners.add(partner)
    

        if not self.user.is_staff:
            self.fields["partner"].queryset = self.user.partners.all()



class ProductForm(OscarProductForm):
    class Meta(OscarProductForm.Meta):
        fields = OscarProductForm.Meta.fields + ['condition']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class':'form-control'})
        self.fields['condition'].widget.attrs.update({'class':'form-select'})
        self.fields['is_public'].widget.attrs.update({'class':'form-check'})
        self.fields['upc'].widget.attrs.update({'class':'form-control'})
        self.fields['description'].widget.attrs.update({'class':'form-control', 'cols':40, 'rows': 5, 'placeholder':'Give a product description'})

class ProductClassForm(OscarProductClassForm):
    class Meta(OscarProductClassForm.Meta):
        model = ProductClass
        fields = ["name", "category", "requires_shipping", "track_stock", "options"]
    
    

apps/dashboard/catalogue/views.py
from oscar.apps.dashboard.catalogue.views import ProductCreateUpdateView , ProductClassCreateView as OscarProductClassCreateView
from oscar.apps.dashboard.catalogue.views import ProductListView as OscarProductListView

from django.urls import reverse
from django.shortcuts import render

from .forms import ProductForm, ProductClassForm
from .formsets import StockRecordFormSet
from .tables import ProductTable


class ProductListView(OscarProductListView):
    table_class = ProductTable


class TlinkProductCreateUpdateView(ProductCreateUpdateView):
    template_name = "store/dashboard/product_addition.html"
    form_class = ProductForm
    stockrecord_formset = StockRecordFormSet

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.formsets = {
            "image_formset": self.image_formset,
            "stockrecord_formset": self.stockrecord_formset,
        }


    def form_valid(self, form ,*args, **kwargs):
        product = form.save(commit=False)
        product.seller = self.request.user
        product.save()
        
        # Add the product to the current user's store
        self.request.user.shop.record.products.add(product)
        product.categories.add(self.get_context_data()['product_class'].category)
    
        response = super().form_valid(form, *args, **kwargs)

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def get_success_url(self, **kwargs):
        super().get_success_url(**kwargs)
        action = self.request.POST.get("action")
        if action == "continue":
            url = reverse("dashboard:catalogue-product", kwargs={"pk": self.object.id})
        else:
            url = reverse("store:dashboard", kwargs={'pk':self.request.user.pk})
        return self.get_url_with_querystring(url)

        
class ProductClassCreateView(OscarProductClassCreateView):
    form_class= ProductClassForm
    
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

store/templates/store/profile.html
{% extends 'store/baseaccount.html' %}
{% load static %}
{% load image_tags %}
{% load i18n %}

{% block profile_tabcontent %}
<div class="fw-bold fs-3">
    <h3>Profile</h3>
    <hr>
</div> 
<table class="table table-striped table-bordered">
    <tbody>
        <tr>
            <th>{% trans 'Name' %}</th>
            <td>{{ user.get_full_name|default:'-' }}</td>
        </tr>
        <tr>
            <th>{% trans 'Email address' %}</th>
            <td>{{ user.email }}</td>
        </tr>
        {% block profile_fields %}
            {% for field in profile_fields %}
                <tr>
                    <th>{{ field.name }}</th>
                    <td>{{ field.value|default:"-" }}</td>
                </tr>
            {% endfor %}
        {% endblock %}
        <tr>
            <th>{% trans 'Date registered' %}</th>
            <td>{{ user.date_joined }}</td>
        </tr>
    </tbody>
</table>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a href="{% url 'store:change-password' %}" class="btn btn-primary">{% trans 'Change password' %}</a>
    <a href="{% url 'store:profile-update' %}" class="btn btn-primary">{% trans 'Edit profile' %}</a>
    <a id="delete_profile" href="{% url 'store:profile-delete' %}" class="btn btn-danger">{% trans 'Delete profile' %}</a>
</div>


{% endblock %}

store/templates/store/settings.html
{% extends 'core/base.html' %}
{% load static %}
{% load image_tags %}

{% block main-content %}
<div style="height: 100px; margin-bottom: 20px;" ></div>
<div class="settings_body container-fluid my-4">
    
    <div class="modal fade " tabindex="-1" id="shop_prompt" data-bs-backdrop="static"  role="dialog" data-bs-keyboard="false" aria-labelledby="shop_promptlabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title ">Want to make money!!! </h4>       
                </div>
                <div class="modal-body">
                    <p class="fw-medium fs-6">
                        Fill in the form to create your own store and unlock more features to sell with us
                    </p>
                </div>
                <div class="modal-footer">    
                    <span class="btn btn-success" data-bs-dismiss="modal" >Ok</span>
                    <a href="" class="btn btn-danger">Maybe Later</a>
                </div>
    
            </div>
        </div>
     </div>
    <style>
        .profile-image{
            width: 12rem;
            height: 12rem;
            border-radius: 50%;
            border: 6px solid rgba(255, 255, 255, 0.15);
            margin: 5px auto;
        }
    </style>
    <nav aria-label="breadcrumb d-inline-block">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'core:index' %}">Home</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="{% url 'store:settings'  %}">Settings</a>
            </li>
        </ol>
     </nav>
    
     <h3 class="me-auto">Account Settings</h3>
     
     {% if messages %}
     {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show  box fw-bold fs-6" role="alert">
        <p>{{ message }}</p>
        <span class="btn-close" data-bs-dismiss="alert" aria-label="Close"></span>
         </div>
        {% endfor %}
    {% endif %}
     <hr>
    <div class="d-flex justify-content-sm-end justify-content-center flex-wrap-wrap">
        <div class=""> 
            <img src="{{ user.profile.url }}" alt="" class="profile-image img-fluid" id="profileImage">
        </div>
        <form  class=" pt-container align-self-center " id="profileForm">
            {% csrf_token%}
            <label for="imageInput">
                <span class="btn btn-primary text-white fw-bold" id="updateImageButton">Edit image</span>
                <input type="file" name="profile-image" class="d-none" id="imageInput" onchange="uploadImage()">
            </label>
        </form>
    </div>
   
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-store-tab" data-bs-toggle="tab" data-bs-target="#nav-store" type="button" role="tab" aria-controls="nav-store" aria-selected="true">Store settings</button>
            <button class="nav-link " id="nav-userInfo-tab" data-bs-toggle="tab" data-bs-target="#nav-userInfo" type="button" role="tab" aria-controls="nav-userInfo" aria-selected="false">User settings</button>
            <button class="nav-link " id="nav-referral-tab" data-bs-toggle="tab" data-bs-target="#nav-referral" type="button" role="tab" aria-controls="nav-referral" aria-selected="false">Referral settings</button>
            <button class="nav-link " id="nav-makeMoney-tab" data-bs-toggle="tab" data-bs-target="#nav-makeMoney" type="button" role="tab" aria-controls="nav-makeMoney" aria-selected="false">How to make money with Tlink</button>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-store" role="tabpanel" aria-labelledby="nav-store-tab" tabindex="0">
            <div class="container-fluid">
            <form action="{% url 'store:createStore' pk=user.id %}" method="POST" enctype="multipart/form-data" class="row g-3">
                    {% csrf_token %}
                    {% if storeForm.errors %}
                    <div class="alert alert-danger alert-dismissible fade show  box fw-bold fs-6" role="alert">
                        {% for field in storeForm %}
                        {% if field.errors %}
                        {{field.label_tag}}
                        {{field.errors}}
                        {% endif %}
                        {% endfor %}
                        <span class="btn-close" data-bs-dismiss="alert" aria-label="Close"></span>
                    </div>
                    {% endif %}
                    <div class="fw-bold fs-3">
                        {% if user.shop.pk and user.shop.get_slug %}
                        <h3>Edit Store</h3>
                        {% else %}
                        <h3>Create your online store</h3>
                        {% endif %}
                    </div> 
                <div class="my-2">
                    {{storeForm.non_field_errors}}
                </div>
                <div class="col-md-6">
                    <label for="{{ storeForm.name.id_for_label }}" class="form-label fw-blod">Name your store:</label>
                    {{storeForm.name}}
                </div>
                <div class="col-md-6">
                    <label for="{{ storeForm.location.id_for_label }}" class="form-label fw-blod">Location:</label>
                    {{storeForm.location}}
                </div>       
                
                <div class=" row my-3">
                    <div>
                        <h5 class="fw-bold fs-5">Do you have a shop on ground?</h5>
                        <p class="fw-medium">Include pysical shop images(Optional)</p>
                    </div> 
                    
                    <div class="col-md-3 bordered mt-2 col-6 ">
                        {{storeForm.location_image1.errors}}
                        <div class="card border {% if storeForm.location_image1.errors %} border-danger {% else %}border-primary{% endif %} border-4" id="card1">
                            <div class="card-header text-center" id="imageName1">Location image 1</div>
                            <div class="card-image">
                            <img src="{% oscar_thumbnail user.shop.location_image1 '400x300' crop='center' upscale='False' %}" class="img-fluid rounded " alt="Location image 1">
                            <div class="card-body">
                              <label for="{{storeForm.location_image1.id_for_label }}">
                                <a class="btn btn-primary">Edit image</a>
                                <div class="d-none">
                                    {{ storeForm.location_image1 }}
                                </div>
                              </label>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 bordered  mt-2 col-6 ">
                        {{storeForm.location_image2.errors}}
                        <div class="card border border-primary border-4" id="card2">
                            <div class="card-header text-center" id="imageName2">Location image 2</div>
                            <div class="card-image">
                                <img src="{% oscar_thumbnail user.shop.location_image2 '400x300' crop='center' upscale='False' %}" class="img-fluid rounded " alt="Location image 2">
                            <div class="card-body">
                              <label for="{{storeForm.location_image2.id_for_label }}">
                                <a class="btn btn-primary">Edit image</a>
                                <div class="d-none">
                                    {{ storeForm.location_image2 }}
                                </div>
                              </label>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 bordered  mt-2 col-6">
                        {{storeForm.location_image3.errors}}
                        <div class="card border border-primary border-4" id="card3">
                            <div class="card-header text-center" id="imageName3">Location image 3</div>
                            <div class="card-image">
                                <img src="{% oscar_thumbnail user.shop.location_image3 '400x300' crop='center' upscale='False' %}" class="img-fluid rounded " alt="Location image 3">
                            <div class="card-body">
                              <label for="{{storeForm.location_image3.id_for_label }}">
                                <a class="btn btn-primary">Edit image</a>
                                <div class="d-none">
                                    {{ storeForm.location_image3}}
                                </div>
                              </label>
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 bordered  mt-2 col-6">
                        {{storeForm.location_image4.errors}}
                        <div class="card border border-primary border-4" id="card4">
                            <div class="card-header text-center" id="imageName4">Location image 4</div>
                            <div class="card-image">
                                <img src="{% oscar_thumbnail user.shop.location_image4 '400x300' crop='center' upscale='False' %}" class="img-fluid rounded " alt="Location image 4">
                            <div class="card-body">
                              <label for="{{storeForm.location_image4.id_for_label }}">
                                <a class="btn btn-primary">Edit image</a>
                                <div class="d-none">
                                    {{ storeForm.location_image4 }}
                                </div>
                              </label>
                            </div>
                            </div>
                        </div>
                    </div>

                    <script>
                       
                       function  imageUploaded(elem, cardid, imageNamediv){
                        card = document.getElementById(cardid)
                        divName = document.getElementById(imageNamediv)
                        
                  
                        if (elem.files[0]){
                            originalName = divName.textContent
                           card.className =  card.className.replace('border-primary', 'border-success ')
                           divName.innerHTML = elem.files[0].name

                        } else {
                           card.className =  card.className.replace('border-success', 'border-primary ')
                           divName.innerHTML = originalName
                           console.log(originalName)
                        }
                       }
                    </script>

                </div>
                <div class="d-grid text-center">
                    <button class="btn btn-success w-25 fw-bold" type="submit">Save</button>
                </div>
                
            </form>
        </div>
        </div>
        <div class="tab-pane" id="nav-userInfo" role="tabpanel" aria-labelledby="nav-userInfo-tab" tabindex="0">UserInfo</div>
        <div class="tab-pane" id="nav-referral" role="tabpanel" aria-labelledby="nav-referral-tab" tabindex="0">Referral</div>
        <div class="tab-pane" id="nav-makeMoney" role="tabpanel" aria-labelledby="nav-makeMoney-tab" tabindex="0">MakeMoney</div>
    </div>

{% block extrascripts %}
<script>
     function uploadImage(){
            const form = document.getElementById('profileForm')
            const formData = new FormData(form)

            fetch("{% url 'store:profile_upload' %}", {
                method: 'POST',
                body: formData,
                headers:{
                    'X-CSRFToken': document.getElementsByName('csrfmiddlewaretoken')[0].value,
                },
            })
            .then(response => response.json())
            .then(data => {
                console.log(data);
                document.getElementById('profileImage').src = data.new_image
            })
            .catch(error => console.error('Error:', error))
        }
</script>


{% if not user.shop.prompted and not user.shop.get_slug %}
<script>
	$(document).ready(function(){
		$("#shop_prompt").modal('show');
	});

</script>

{% endif %}
{{ block.super  }}
{% endblock %}
     
</div>
{% endblock main-content %}

store/templates/store/store_settings_details.html
{% extends 'store/profile.html' %}
{% load static %}
{% load image_tags %}
{% load i18n %}
{% load reviews_tags %}



{% block store_tabcontent %}
{% if user.has_store %}
<div class="fw-bold fs-3">
    <h3>Store Details</h3>
    <hr>
</div> 
<table class="table table-striped table-bordered">
    <tbody>
        <tr>
            <th>{% trans 'Name' %}</th>
            <td>{{ user.shop.name }}</td>
        </tr>
       
        <tr>
            <th>{% trans 'Owner' %}</th>
            <td>{{ user.shop.owner.get_full_name }}</td>
        </tr>
        <tr>
            <th>{% trans 'Location' %}</th>
            <td>{{ user.shop.get_location_display }}</td>
        </tr>
        <tr>
            <th>{% trans 'Rating' %}</th>
            <td>
                <div class="star-rating {{ user.shop.record.rating|as_stars }}  me-auto fs-5">
                    <i class="bi bi-star-fill "></i>
                    <i class="bi bi-star-fill"></i>
                    <i class="bi bi-star-fill "></i>
                    <i class="bi bi-star-fill "></i>
                    <i class="bi bi-star-fill"></i>
                </div>
                
            </td>
        </tr>
        <tr>
            <th>{% trans 'Date Created' %}</th>
            <td>{{ user.shop.date_created }}</td>
        </tr>
        
    </tbody>
</table>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a href="{% url 'store:updateStore' %}" class="btn btn-primary">{% trans 'Edit Store' %}</a>
    <a id="delete_profile" href="{% url 'store:profile-delete' %}" class="btn btn-danger">{% trans 'Delete Store' %}</a>
</div>
{% else %}
<h3>You have  no store</h3>
<p>Click the button bellow to create a store.</p>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <a href="{% url 'store:createStore'  %}" class="btn btn-primary">{% trans 'Create Store' %}</a>
</div>
{% endif %}


{% endblock %}