core/urls.py
from django.urls import path, re_path, reverse


from . import views
from apps.dashboard.catalogue.views import TlinkProductCreateUpdateView

app_name='core'
urlpatterns = [
    path('', views.indexList.as_view() , name='index'),
    path('search/', views.ProductStoreSearch.as_view(), name='search'),
    path('subscribe/', views.Subscribe.as_view(), name='subscribe'),
    re_path(
                r"^products/create/(?P<product_class_slug>[\w-]+)/$",
                TlinkProductCreateUpdateView.as_view(),
                name="catalogue-product-create",
            ),
]

store/urls.py
from django.urls import path, re_path

from . import views
from apps.dashboard.catalogue import views as  OscarViews

app_name='store'
urlpatterns = [
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('settings/store/update', views.StoreCreationView.as_view(), name='updateStore'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/delete/', views.ProfileDeleteView.as_view(), name='profile-delete'),
    path('profile/change_password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('<int:pk>/follow/store/', views.FollowView.as_view(), name='follow'),
    path('<int:pk>/dashboard/', views.DashBoardView.as_view(), name='dashboard'),
    path('product_addition/<str:category>/', views.ProductCreation.as_view(), name='add_product'),
    path('<int:pk>/<slug:slug>/store', views.StoreView.as_view(), name='store'),
    path('upload-profile-image/', views.UploadProfileImageView.as_view(), name='profile_upload'),
    path('filter/products_by/<str:product_class>/<int:pk>/<slug:slug>', views.ProductClassFilterView.as_view(), name='productclass'),
    path('<int:pk>/<slug:slug>/comment-on-store/', views.StoreCommentView.as_view(), name="comment"),
    path('<int:pk>/vote/comment', views.AddVoteView.as_view() , name='add-vote'),
    path('<int:comment_pk>/reply/comment', views.CommentReplyView.as_view(), name='reply'),
    path('create/store/settings', views.StoreCreationView.as_view(),  name="createStore"),
    re_path(
                r"^products/create/(?P<product_class_slug>[\w-]+)/$",
                OscarViews.TlinkProductCreateUpdateView.as_view(),
                name="product_create",
            ),
   
]

tlink_django/urls.py
from django.conf import settings
from django.apps import apps
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('tlink/', include('store.urls')),
    path('', include(apps.get_app_config('oscar').urls[0])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

apps/catalogue/models.py
from unicodedata import category
from oscar.apps.catalogue.abstract_models import AbstractProduct as BaseProduct, AbstractProductClass as BaseAbstractProductClass
from oscar.apps.catalogue.abstract_models import AbstractCategory as OscarAbstractCategory


from django.db import models
from django.urls import reverse

from core.models import User


class Category(OscarAbstractCategory):
    pass

class ProductClass(BaseAbstractProductClass):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    
class Product(BaseProduct):
    CONDITION_CHOICES = [
        ('N', 'New'),
        ('U', 'Used')
    ]
    condition = models.CharField(max_length = 2, choices=CONDITION_CHOICES)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)




from oscar.apps.catalogue.models import * 

core/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import Group

import datetime

from oscar.apps.customer.abstract_models import AbstractUser


class User(AbstractUser):
    GENDER_CHOICES = [("M","Male"), ("F", "Female")]
    LOCATION_CHOICES = [("BW", "Bweyale"), ("KY", 'Kyradongo')]
    phone_number = models.CharField(max_length=13)
    whatsApp = models.CharField(max_length=13, blank=True, null=True)
    date_of_birth = models.DateField(default=datetime.date(2024,1,1))
    location = models.CharField(max_length=2, choices=LOCATION_CHOICES)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    has_accepted_terms_and_conditions = models.BooleanField(default=False)
    profile_image = models.ImageField(upload_to='profiles', default='blank-profile.png')

    @property
    def has_store(self):
        return hasattr(self, 'shop')

core/forms.py
from django.forms import ModelForm,TextInput, PasswordInput, CharField, ValidationError
from core.models import User

class UserCreationForm(ModelForm):
    confirm_password = CharField(widget=PasswordInput, help_text='Enter the same password as above')
    class Meta:
        model = User
        fields = ( 'email', 'phone_number',  'password','confirm_password', 'gender', 'date_of_birth', 'location', 'profile_image')

        widgets = {
            'password': PasswordInput(attrs={'class': 'has-text-warning'})
        }

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError('Passwords do not match.')
    

core/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models import Q
from django.conf import settings
from django.views.generic import ListView,  TemplateView
from apps.catalogue.models import Product
from django.core.paginator import Paginator

from store.models import Store
from .models import User
from .mixins import BaseContextMixin

from apps.catalogue.models import Category


def get_category_products(category):
    category_products = []
    products = Product.objects.all()

    for product in products:
        product_cat = product.get_categories()[0]
        if product_cat.get_root() == category:
            category_products.append(product)

    return category_products



class indexList(BaseContextMixin, ListView):
    model = Product
    template_name = 'core/index.html'
    context_object_name = 'products'
    paginate_by = settings.STORE_PRODUCTS_PER_PAGE

    def get_queryset(self):
        queryset = Product.objects.all().browsable().base_queryset()  
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        categories = Category.objects.all()
        root_categories = []
       
        for category in categories:
            if category.is_root():
                root_categories.append(category)
        
        stores = Store.objects.all()

        context['categories'] = root_categories
        context['stores'] = stores
        print(context)
        return context

class Subscribe(TemplateView):
    template_name = 'core/pricing.html'


class ProductStoreSearch(BaseContextMixin, ListView):
    model = Product
    template_name = 'core/results.html'
    context_object_name = 'products'
    paginate_by = settings.STORE_PRODUCTS_PER_PAGE
    tab = 'products'

    def get_queryset(self):
        # Product search
        self.q = self.request.GET.get('q', '').strip()
        queryset = Product.objects.filter(Q(title__icontains=self.q)).browsable().base_queryset()
        return queryset
    

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        # Store search
        stores = Store.objects.filter(Q(name__icontains=self.q))
        store_paginator = Paginator(stores,settings.STORE_PRODUCTS_PER_PAGE)
        page_number = self.request.GET.get("store_page")
        store_page_obj = store_paginator.get_page(page_number)
        context['store_paginator'] = store_paginator
        context['store_page_obj'] = store_page_obj
        context['stores'] = stores
        context['q'] = self.q
        context['tab'] = self.set_tab()
        print(context)
        return context
    
    def set_tab(self):
        urlTab = self.request.GET.get('tab')

        print('requet.GEt objects ', self.request.GET)
        if urlTab == 'store':
            return 'store'
        return self.tab
        
            
   

core/templates/core/base.html
{% extends 'oscar/base.html' %}

{% block layout %}
 <!--Navbar-->
 <nav class="primary-nav navbar navbar-dark bg-dark navbar-expand-lg fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand me-auto" href="{% url 'core:index' %}">{{ site_name_short }}</a>
      
      <div class="offcanvas text-bg-dark offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{{ site_name }}</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link mx-lg-2 active" aria-current="page" href="{% url 'core:index' %}">Home</a>
            </li>
            {% if user.is_authenticated  %}
            {% if user.shop.pk and user.shop.get_slug %}
            <li class="nav-item">
              <a class="nav-link mx-lg-2" href="{% url 'store:store' user.shop.pk user.shop.get_slug %}">MyStore</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-lg-2" href="{% url 'store:dashboard' user.pk %}">Dashboard</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link mx-lg-2" href="{% url 'store:settings'  %}">Account</a>
            </li>
            {% endif %}
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link mx-lg-2" href="{% url 'dashboard:index' %}">Oscar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-lg-2" href="/admin">Admin</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle mx-lg-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                {% for category in base_categories %}
                <li><a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <form class="d-flex me-3 mt-3 mt-lg-0 " role="search" action="{% url 'core:search' %}" >
            <input value="{% if q %} {{ q }} {% endif %}" class="form-control me-2" type="search" name='q' placeholder="Search product or store" aria-label="Search">
            <button class="btn btn-outline-primary" type="submit">Search</button>
          </form>

        </div>
      </div>
      {% if user.is_authenticated %}
      <a href="{% url 'customer:logout' %}" class="login_or_register_action_btn btn  btn-primary">Logout</a>
      {% else %}
      <a href="{% url 'customer:login' %}" class="login_or_register_action_btn btn  btn-primary">Signin</a>
      {% endif %}
      <button class="navbar-toggler pe-auto" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>
  <!--End of Navbar-->
  
  {% block main-content %}{% endblock %}
  {% include 'oscar/partials/backtotop.html' %}
  {% include 'oscar/partials/footer.html' %}
  {% endblock layout %}

core/templates/core/base_login_and_registration.html
{% extends 'core/base.html' %}
{% load static %}
{% block main-content %}

<div style="height: 40px;"></div>
<div class="container d-flex justify-content-center align-items-center  min-vh-100 my-3">

    <div class="row border rounded-5 p-3 bg-white shadow box-area mb-3">
        <!--=================Left divison=========================-->
        <div class="col-md-6 col-sm-3 rounded-4 d-flex justify-content-center align-items-center flex-column left-box bg-primary" >
            <div class="featured-image">
                <img src="{% static 'core/Images/1.png' %}" alt="" class="img-fluid" style="width:250px">
               <p class="text-white fs-2" style="font-family: 'Courier New', Courier, monospace; font-weight: 600px;">
                   TrustLink
                </p>
                <small class="text-white text-warp" style="width:17rem; font-family: 'Courier New', Courier, monospace;">The best online shopping experience</small>
            </div>
           
        </div>
        <!--=================Right divison=========================-->
        <div class="col-md-6 col-sm-9 right-box">
            <div class="row align-items-center">
                <div class="header-text mb-4">
                    <h2 class="text-center">{% block form_label %}{% endblock %}</h2>
                    <h3>{% block greeting_intro %}{% endblock %}</h3>
                    <p>{% block greeting %}{% endblock %}</p>
                </div>
                <form action="{{ request.get_full_path }}" method="POST">
                    {% csrf_token %}
                   {% block form_content %}{% endblock %}
                </form>
            </div>
        </div>
    </div>

    <style>
        .box-area{
            width: 930px;
        }

        .right-box{
            padding: 40px 30px 40px 40px;
        }

        @media only screen and (max-width: 768px){
            .box-area{
                margin: 0 10px;
            }

            .left-box {
                height: 100px;
            }

            .right-box{
                padding: 20px;
            }
        }
    </style>
    
</div>
{% endblock %}

core/templates/core/image.html
{% extends 'oscar/layout.html' %}
{% load static %}
<!-- {% load image_tags %} -->
 
{% block layout %}
{# Top-horizontal bar with account, notifictions, dashboard links #}
{% include "oscar/partials/nav_accounts.html" %}


{# Site logo/title, mini-basket, browse dropdown and searchbox #}
<header class="header">  
    {% block navigation %}
        {% include "oscar/partials/nav_primary.html" %}
    {% endblock %}
</header>

<section class="mt-5">
   <div class="has-text-centered columns">
    <div class="column is-half">
        <div class="card">
            <div class="card-image">
              <figure class="image">
                <section id="portfolio" class="portfolio">
                    <div class="portfolio-container">
    
                      <div class="portfolio-item filter-app">
                        <div class="portfolio-wrap">
                          <img src="{% oscar_thumbnail product.primary_image.original 'x155' %}" alt='Image' class="image itemImage"> 
                          <div class="portfolio-info">
                            <h4>App 1</h4>
                            <p>App</p>
                            <div class="portfolio-links">
                              <a href="../assets/Images/post_images/photo-55.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 1"><i class="bx bx-plus"></i></a>
                              <a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details"><i class="bx bx-link"></i></a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                 </section><!-- End Portfolio Section -->
              </figure>
            </div>
            <div class="card-content p-3 card-info ">  
            <div class="content"> 


              


              <div class="column ">
               
              </div>

core/templates/core/index2.html
{% extends 'oscar/layout.html' %}
{% load static %}
{% load image_tags %}
{% load i18n %}
 
{% block layout %}

{# Site logo/title, mini-basket, browse dropdown and searchbox #}
<header class="header">  
    {% block navigation %}
        {% include "oscar/partials/nav_primary.html" %}
    {% endblock %}
</header>
<section class="main-section mt-5">
    <div class="container-fluid">
        <div class="columns">
            <div class="column is-one-third">
              <aside class="panel is-info ">
                <p class="panel-heading">
                  Categories
                </p>
                <p class="panel-tabs">
                  <a href="" class="is-active">All</a>
                  <a href="">Public</a>
                  <a href="">Private</a>
                  <a href="">Source</a>
                  <a href="">Forks</a>
                </p>
                <div class="panel-block">
                  <p class="control has-icons-left">
                    <input type="text" class="input is-info" placeholder="Search">
                    <span class="icon is-left">
                      <i class="bi bi-search"></i>
                    </span>
                  </p>
                </div>
                <a class="panel-block is-active">
                  <span class="panel-icon">
                    <i class="bi bi-gender-female"></i>
                  </span>
                  Fashion
                </a>
                <a class="panel-block is-active">
                  <span class="panel-icon">
                    <i class="bi bi-phone"></i>
                  </span>
                  Electronics
                </a>
                <div class="panel-block">
                  <button class="button is-link is-outlined is-fullwidth">
                    Reset all filters
                  </button>
              </div>
              </aside>
            </div>
            <div class="column ">
              <div class="hero is-medium is-link">
      
                <div class="hero-body">
                  <h1 class="title">Tlink</h1>
                  <h5 class="subtitle">The best online Market</h5>
                </div>
                <div class="hero-foot">
                <nav class="tabs is-boxed is-fullwidth">
                  <div class="container">
                    <ul>
                      <li class="is-active">
                        <a>Overview</a>
                      </li>
                      <li>
                        <a>Fashion</a>
                      </li>
                      <li>
                        <a>Electronics</a>
                      </li>
                      <li>
                        <a>Health & Beauty</a>
                      </li>
                      <li>
                        <a>Supermarket</a>
                      </li>
                      <li>
                        <a>Phones & Tablets</a>
                      </li>
                    </ul>
                  </div>
                </nav>
              </div>
      
              </div>
            </div>
      
        </div>
        <div class="section">
          <h3 class="title has-text-centered">
            Top products
          </h3>
          <div class="section" >
            <div class="columns">
                <!--Swiper container-->
            <div class="swiper column "> 
              <div class="swiper-wrapper">
                {% for product in products %}
                <div class="swiper-slide column is-full-mobile is-half-tablet is-narrow is-3">
                  <div class="container">
                  <div class="card W-100">
                    <div class="card-image">
                      <figure class="image">
                        <section id="portfolio" class="portfolio">
                            <div class="portfolio-container">
            
                              <div class="portfolio-item filter-app">
                                <div class="portfolio-wrap">
                                  <img src="{% oscar_thumbnail product.primary_image.original '300x400' crop='center' upscale=False  %}" alt='Image' class="image  itemImage"> 
                                  <div class="portfolio-info">
                                    <h4>{% trans product.get_title %}</h4>
                                    <p>App</p>
                                    <div class="portfolio-links">
                                      <a href="../assets/Images/post_images/photo-55.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 1"><i class="bx bx-plus"></i></a>
                                      <a href="portfolio-details.html" class="portfolio-details-lightbox" data-glightbox="type: external" title="Portfolio Details"><i class="bx bx-link"></i></a>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                         </section><!-- End Portfolio Section -->
                      </figure>
                    </div>
                    <div class="card-content p-3 card-info ">  
                    <div class="content has-text-centered">
                        <p class="title is-size-6 has-text-weight-blod "  style="height: 40px;">{{ product.get_title|truncatewords:3 }}</p>
                        <p class="subtitle is-size-6 p-1 has-text-primary has-text-weight-semibold">Ugx 100,000</p>
                      </div>
              </div>
                </div>
                </div>
                </div><!--End of slide 1-->
                {% endfor %}
                
              </div>
              <div class="swiper-pagination"></div>
              <div class="swiper-button-prev"></div>
              <div class="swiper-button-next"></div>
              <div class="swiper-scrollbar"></div>
            </div>
              
            </div>
          </div>
        </div>
        <div class="columns">
          <div class="column has-text-centered title">
            <h1 class="title">Side bar</h1>
          </div>
          <div class="column">
            <h1>The body</h1>
          </div>
        </div>
    </div>
</section>

{% include "oscar/partials/footer.html" %}
{% endblock layout %}
 

core/templates/core/layout.html
{% extends 'core/base.html' %}
{% load static %}
{% load category_tags %}
{% load image_tags %}
{% load purchase_info_tags %}
{% load i18n %}
{% load currency_filters %}
{% block main-content %}
<div class="category-main-banner {{ category.get_root.name.lower }} d-flex">
    <div class="category-header-info  justify-content-center align-items text-center">
        <h1 class="text-white ">Welcome to {{ site_name }}</h1>
        <h5 class="text-white fw-bold fst-italic "> {{ category.name.title  }} Collection</h5>
    </div>
</div>

<div class="container-fluid my-2 ps-3">
    <nav aria-label="breadcrumb" >
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:index' %}" class="fw-bold fs-6">Home</a></li>
            {% for ancestor in category.get_ancestors %}
            <li class="breadcrumb-item"><a href="{{ ancestor.get_absolute_url }}" class="fw-bold fs-6">{{ ancestor.name }}</a></li>
            {% endfor %}
            <li class="breadcrumb-item active" aria-current="page"><a href="{{ category.get_absolute_url }}" class="fw-bold fs-6">{{ category.name }}</a></li>
        </ol>
    </nav>
</div>
<div class="container-fluid my-2">
    <div class="row justify-content-center">
        <div class="col-3 d-none d-mb-block d-lg-block"><!--Medium device Category list-->
            <div class="card">
                <div class="card-header">
                    <h4 class="fs-bold">Show Resuls for:</h4>
                </div>

                <div class="card-content">
                    {% category_tree parent=category.get_root as tree_categories  %}
                        <ul>
                        {% for category, info in tree_categories %}
                            <li>
                                {% if category.productclass_set.all.exists %}
                                {{ category }} has product class
                                {% endif %}
                                <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                                {% if info.has_children %}
                                   <ul>
                                {% else %}
                                    </li>
                                {% endif %}
                            {% for n in info.num_to_close %}
                                </ul></li>
                            {% endfor %}
                        {% endfor %}
                    </ul> 

                </div>
            </div>
        </div><!--End of medium device Category list-->
        {% block category_content %}
        <div class="col-9">  
            <div class="my-3 p-2 d-mb-none d-lg-none"> <!--Mobile Category list--> 
                
                <div class="d-grid">
                    <button class="btn btn-outline-primary fs-5 fw-bold" data-bs-toggle="collapse" data-bs-target="#category-collapse" role="button" aria-expanded="false" aria-controls="category-collapse">
                        {{ category.get_root.name }} Categories
                    </button>
                </div>
                <div class="collapse" id="category-collapse">
                    <div class="card card-body mt-1">
                    {% category_tree parent=category.get_root as tree_categories  %}
                    <ul>
                    {% for category, info in tree_categories %}
                        <li>
                            <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                            {% if info.has_children %}
                               <ul>
                            {% else %}
                                </li>
                            {% endif %}
                        {% for n in info.num_to_close %}
                            </ul></li>
                        {% endfor %}
                    {% endfor %}
                </ul> 
                    </div>
            </div> 
            </div> <!--End of Mobile category list-->            
            {% block category_description %}
            {% if category.description %}
                <div class="card mb-3 d-none d-mb-block d-lg-block" style="max-width: 760px;">
                    <div class="row g-0 ">
                        <div class="col-4">
                            <img src="{% oscar_thumbnail category.image 'x250' upscale=False %}" alt="" class="img-fluid rounded-start">
                        </div>
                        <div class="col-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ category.name }}</h5>
                                 {{ category.description|safe }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endblock %}

            <!--Find your interests section-->
            <div class="text-center">
                <h3>Find you interest</h3>
                <hr>
            </div>
            {% if category.get_children.count > 1%}
            {% include 'core/partials/subcategorySlider.html'  %}
            {% else %}
            {% include 'core/partials/subcategorySlider.html' with category=category.get_root %}
            {% endif %}
            <!--End of find your interests section-->
         
        </div>
            {% endblock category_content %}
    </div><!--End of row-->

    <div class="container-fluid" >
        <div class="text-captialise text-center my-3">
            <h2>{{ category.get_root }} Vendors</h2>  
        </div>
        
        {% include 'core/partials/storeList.html' %}

        <div class="text-captialise text-center my-3">
            <h2 id="feature_products">Featured {{ category.name }} products</h2>  
        </div>

        {% include 'core/partials/paginatedProductMixture.html' with slider_id='feature_products' %}
    </div>
  
</div>
{% endblock %}

core/templates/core/register.html
{% extends 'core/base_login_and_registration.html' %}

{% block greeting_intro %}Hello There, {% endblock %}
{% block greeting %}Your welcome to join our <a href="{% url 'core:index' %}">TLink</a> community{% endblock %}

{% block form_label %} Signup {% endblock %} 
{% block form_content %}
<div class="row">
    {% if form.errors or form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissible fade show  box fw-bold fs-6" role="alert">
                        {% for field in form %}
                        {% if field.errors %}
                        {{field.label_tag}}
                        {{field.errors}}
                        {% endif %}
                        {% endfor %}
                        {{form.non_field_errors}}
                        <span class="btn-close" data-bs-dismiss="alert" aria-label="Close"></span>
                    </div>
                    {% endif %}
    {{ form.redirect_url }}
    <div class="col-md-6 my-1">
        <label for="{{form.first_name.id_for_label }}" class="form-label">First name:</label>
        {{ form.first_name }}
    </div>
    <div class="col-md-6 my-1">
        <label for="{{form.last_name.id_for_label }}" class="form-label">Last name:</label>
        {{ form.last_name }}
    </div>
    <div class="col-md-6 my-1">
        <label for="{{form.email.id_for_label }}" class="form-label">Email:</label>
        {{ form.email }}
    </div>
    <div class="col-md-6 my-1">
        <label for="{{form.location.id_for_label }}" class="form-label">Location:</label>
        {{ form.location }}
    </div>
    <div class="col-md-6 my-1">
        <label for="{{form.phone_number.id_for_label }}" class="form-label" >Phone Number:</label>
        {{ form.phone_number }}
    </div>
    <div class="col-md-6 my-1">
        <label for="{{form.whatsApp.id_for_label }}" class="form-label" >WhatsApp Number</label>
        {{ form.whatsApp }}
    </div
    <div class="col-md-6 my-1">
        <label for="{{form.gender.id_for_label }}" class="form-label" >Gender:</label>
        {{ form.gender}}
    </div>
    <div class="row">
        <label for="{{form.date_of_birth.id_for_label}}">Date of Birth:</label>
        {{ form.date_of_birth }}
    </div>
    <div class="col-md-6 my-1">
        <label for="{{form.password1.id_for_label }}" class="form-label" >Password:</label>
        {{ form.password1 }}
    </div>
    <div class="col-md-6 my-1">
        <label for="{{form.password2.id_for_label }}" class="form-label" > Confirm Password:</label>
        {{ form.password2 }}
    </div>
    <div class="col-12 my-1">
       <p class="mb-1">I have read and accepted the <a href="" class="fw-bold">Terms and conditions</a></p>
        {{ form.has_accepted_terms_and_conditions }}
    </div>

    <p class="my-1 fs-6 fw-bold">Already have an account? <a href="{% url 'customer:login' %}">Login</a></p>

    <button name="registration_submit" type="submit" value="Register" class="btn btn-lg btn-primary w-100 my-2" >Register</button>

</div>
{% endblock form_content %}