core/urls.py
from django.urls import path, re_path, reverse


from . import views
from apps.dashboard.catalogue.views import TlinkProductCreateUpdateView

app_name='core'
urlpatterns = [
    path('', views.indexList.as_view() , name='index'),
    path('search/', views.ProductStoreSearch.as_view(), name='search'),
    path('subscribe/', views.Subscribe.as_view(), name='subscribe'),
    re_path(
                r"^products/create/(?P<product_class_slug>[\w-]+)/$",
                TlinkProductCreateUpdateView.as_view(),
                name="catalogue-product-create",
            ),
]

tlink_django/urls.py
from django.conf import settings
from django.apps import apps
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('tlink/', include('store.urls')),
    path('', include(apps.get_app_config('oscar').urls[0])),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

templates/oscar/partials/backtotop.html
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

templates/oscar/partials/footer.html
{% block footer %}
<footer class="container-fluid has-background-grey ">
    <div class="columns">
        <div class="column">
            <ul class="ul">
                <li class="title is-6 has-text-info-light">
                    <i class="bi bi-facebook"></i>
                    <span class="">Facebook</span>
                </li>
                <li class="title is-6 has-text-info-light ">
                    <i class="bi bi-instagram"></i>
                    <span class="">Insatgram</span>
                </li>
                <li class="title is-6 has-text-info-light ">
                    <i class="bi bi-whatsapp"></i>
                    <span class="">Facebook</span>
                </li>
            </ul>
        </div>
    </div>
</footer>
{% endblock footer %}

templates/oscar/partials/form_field.html
{% load widget_tweaks %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% comment %}
        Make the field widget type available to templates so we can mark-up
        checkbox and radio inputs differently to other widgets.
    {% endcomment %}

    {% block control_group %}
        <div class="form-group{% if style == "horizontal" %} row{% endif %}">

            {% block label %}
                {% if not nolabel and field.widget_type != 'checkbox' %}
                    <label for="{{ field.auto_id }}" class="{% if style|default:"stacked" != 'stacked' %}col-sm-4{% endif %} col-form-label{% if field.field.required %} required{% endif %}">
                        {{ field.label|safe }}
                    </label>
                {% endif %}
            {% endblock %}

            {% block controls %}
                <div class="{% if style|default:"stacked" != 'stacked' %}col-sm-7{% endif %}{% if field.widget_type == 'checkbox' %} form-check{% endif %}">
                    {% block widget %}
                        {% if field.widget_type == 'checkbox' %}
                            <label for="{{ field.auto_id }}" class="col-form-label {% if field.field.required %}required{% endif %}">
                                {% render_field field %}
                                {{ field.label|safe }}
                            </label>
                        {% else %}
                            {% render_field field class+="form-control" %}
                        {% endif %}
                    {% endblock %}

                    {% block errors %}
                        {% for error in field.errors %}
                            <span class="error-block border text-danger fw-bold"><i class="bi bi-exclamation"></i> {{ error }}</span>
                        {% endfor %}
                    {% endblock %}

                    {% block help_text %}
                        {% if field.help_text %}
                            <small class="form-text text-muted">
                                {# We allow HTML within form help fields #}
                                {{ field.help_text|safe }}
                            </small>
                        {% endif %}
                    {% endblock %}
                </div>
            {% endblock %}
        </div>
    {% endblock %}
{% endif %}

templates/oscar/partials/nav_primary.html
{% extends 'oscar/partials/nav_primary.html' %}
{% load i18n %}

{% block nav_extra %}
{% include "oscar/partials/search.html" %}
<a href="{% url 'core:subscribe' %}" class="btn btn btn-primary my-2 mr-3 my-sm-0" >{% trans "Sign up" %}</a>
<a href="{% url 'core:index' %}" class="btn btn btn-primary my-2 my-sm-0 mr-3" >{% trans "Home" %}</a>
<a href="{% url 'dashboard:index' %}" class="btn btn btn-primary my-2 my-sm-0 mr-3" >{% trans "Dashboard" %}</a>
{% endblock %}

templates/oscar/partials/pagination.html
{% load display_tags %}
{% load i18n %}

{% if paginator.num_pages > 1 %}
    <nav class="my-2">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item ">
                    <a class="page-link" href="?{% get_parameters 'page' %}page={{ page_obj.previous_page_number }}&tab=products#{{ slider_id }}" tabindex="-1">
                        {% trans "previous" %}
                    </a>
                </li>
            {% endif %}
            <li class="page-item disabled">
                <span class="page-link bg-primary text-white fw-bold">
                    {% blocktrans with page_num=page_obj.number total_pages=paginator.num_pages %}
                        Page {{ page_num }} of {{ total_pages }}
                    {% endblocktrans %}
                </span>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% get_parameters 'page' %}page={{ page_obj.next_page_number }}&tab=products#{{ slider_id }}">
                        {% trans "next" %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/oscar/partials/search.html
{% load i18n %}

<form class="form-inline mx-auto my-lg-0" method="GET" action="{% url 'search:search' %}">
    <input class="form-control mr-sm-2" name="q" placeholder="{% trans 'Search' %}" aria-label="{% trans 'Search' %}">
    <button class="btn btn btn-primary my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
</form>

templates/oscar/partials/storelist_pagination.html
{% load display_tags %}
{% load i18n %}

{% if store_paginator.num_pages > 1 %}
    <nav class="my-2">
        <ul class="pagination justify-content-center">
            {% if store_page_obj.has_previous %}
                <li class="page-item ">
                    <a class="page-link" href="?{% get_parameters 'store_page' %}{% get_parameters 'tab' %}store_page={{ store_page_obj.previous_page_number }}#{{ slider_id }}&tab=store" tabindex="-1">
                        {% trans "previous" %}
                    </a>
                </li>
            {% endif %}
            <li class="page-item disabled">
                <span class="page-link bg-primary text-white fw-bold">
                    {% blocktrans with page_num=store_page_obj.number total_pages=store_paginator.num_pages %}
                        Page {{ page_num }} of {{ total_pages }}
                    {% endblocktrans %}
                </span>
            </li>
            {% if store_page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% get_parameters 'store_page' %}{% get_parameters 'tab' %}store_page={{ store_page_obj.next_page_number }}&tab=store#{{ slider_id }}">
                        {% trans "next" %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}